### ISSUE TITLE
Safari doesn't have a list of usable fonts

### ISSUE THREAD

**Issue by litherum** [w3cping/font-anti-fingerprinting#13]
> This resembles Safari's list of fonts usable from CSS, which it receives from an OS API.

It isn't a list. We pass a bit to the OS font lookup routines which means "when you do the lookup, please disregard user-installed fonts."

We're in the process of exposing this bit as API for all applications to use.

**Comment by JensenPaul** [comment]
Is there a public issue (radar?) we can track to follow progress on exposing this bit?

@caraitto @asankah

**Comment by litherum** [comment]
Unfortunately there’s nothing public yet.
